import type { AuthAction } from '../auth/rbac.js';

export interface ToolActionInfo {
  action: AuthAction;
  connectionFields?: readonly string[];
  allConnections?: boolean;
}

const connectionFields = ['connection_id', 'connectionId'] as const;

export const TOOL_ACTIONS = {
  audit_filter: { action: 'export' },
  audit_get_recent: { action: 'export' },
  audit_stats: { action: 'export' },
  auth_policy_validate: { action: 'diagnose' },
  auth_whoami: { action: 'diagnose' },
  connection_diagnose: { action: 'diagnose', connectionFields },
  connection_stats: { action: 'diagnose', allConnections: true },
  export_audit: { action: 'export' },
  get_masking_config: { action: 'diagnose' },
  health_check: { action: 'diagnose', allConnections: true },
  list_connections: { action: 'diagnose' },
  manage_masking_rules: { action: 'admin' },
  mongo_aggregate: { action: 'read', connectionFields },
  mongo_begin_transaction: { action: 'write', connectionFields },
  mongo_commit: { action: 'write' },
  mongo_count: { action: 'read', connectionFields },
  mongo_create_index: { action: 'admin', connectionFields },
  mongo_delete_many: { action: 'write', connectionFields },
  mongo_delete_one: { action: 'write', connectionFields },
  mongo_drop_collection: { action: 'admin', connectionFields },
  mongo_execute_in_transaction: { action: 'write' },
  mongo_find: { action: 'read', connectionFields },
  mongo_find_one_and_delete: { action: 'write', connectionFields },
  mongo_find_one_and_update: { action: 'write', connectionFields },
  mongo_insert_many: { action: 'write', connectionFields },
  mongo_insert_one: { action: 'write', connectionFields },
  mongo_list_collections: { action: 'read', connectionFields },
  mongo_list_indexes: { action: 'read', connectionFields },
  mongo_rename_collection: { action: 'admin', connectionFields },
  mongo_rollback: { action: 'write' },
  mongo_schema_analysis: { action: 'read', connectionFields },
  mongo_update_many: { action: 'write', connectionFields },
  mongo_update_one: { action: 'write', connectionFields },
  prometheus_metrics: { action: 'diagnose' },
  query_diff: { action: 'replay' },
  query_history: { action: 'replay', connectionFields },
  query_optimize: { action: 'read', connectionFields },
  query_replay: { action: 'replay', connectionFields },
  query_suggest: { action: 'read', connectionFields },
  redis_blocked_commands: { action: 'diagnose' },
  redis_del: { action: 'write', connectionFields },
  redis_expire: { action: 'write', connectionFields },
  redis_get: { action: 'read', connectionFields },
  redis_hdel: { action: 'write', connectionFields },
  redis_hget: { action: 'read', connectionFields },
  redis_hgetall: { action: 'read', connectionFields },
  redis_hset: { action: 'write', connectionFields },
  redis_llen: { action: 'read', connectionFields },
  redis_lpop: { action: 'write', connectionFields },
  redis_lpush: { action: 'write', connectionFields },
  redis_lrange: { action: 'read', connectionFields },
  redis_pipeline: { action: 'write', connectionFields },
  redis_rpop: { action: 'write', connectionFields },
  redis_rpush: { action: 'write', connectionFields },
  redis_sadd: { action: 'write', connectionFields },
  redis_scan: { action: 'read', connectionFields },
  redis_scard: { action: 'read', connectionFields },
  redis_set: { action: 'write', connectionFields },
  redis_sismember: { action: 'read', connectionFields },
  redis_smembers: { action: 'read', connectionFields },
  redis_srem: { action: 'write', connectionFields },
  redis_ttl: { action: 'read', connectionFields },
  redis_type: { action: 'read', connectionFields },
  redis_zadd: { action: 'write', connectionFields },
  redis_zcard: { action: 'read', connectionFields },
  redis_zrange: { action: 'read', connectionFields },
  redis_zrem: { action: 'write', connectionFields },
  redis_zscore: { action: 'read', connectionFields },
  schema_diff: {
    action: 'read',
    connectionFields: ['source_connection_id', 'target_connection_id'],
  },
  schema_export: { action: 'export', connectionFields },
  server_info: { action: 'diagnose' },
  set_masking_mode: { action: 'admin' },
  sql_batch_execute: { action: 'write', connectionFields },
  sql_begin_transaction: { action: 'write', connectionFields },
  sql_cache_stats: { action: 'diagnose' },
  sql_call_procedure: { action: 'write', connectionFields },
  sql_commit: { action: 'write' },
  sql_create_index: { action: 'admin', connectionFields },
  sql_describe_table: { action: 'read', connectionFields },
  sql_describe_view: { action: 'read', connectionFields },
  sql_execute: { action: 'write', connectionFields },
  sql_execute_in_transaction: { action: 'write' },
  sql_explain: { action: 'read', connectionFields },
  sql_generate_types: { action: 'read', connectionFields },
  sql_list_indexes: { action: 'read', connectionFields },
  sql_list_tables: { action: 'read', connectionFields },
  sql_list_views: { action: 'read', connectionFields },
  sql_query: { action: 'read', connectionFields },
  sql_rollback: { action: 'write' },
  test_connection: { action: 'diagnose', connectionFields },
  validate_connection_config: { action: 'diagnose' },
} as const satisfies Record<string, ToolActionInfo>;

export function getToolActionInfo(toolName: string): ToolActionInfo {
  return TOOL_ACTIONS[toolName as keyof typeof TOOL_ACTIONS] ?? { action: 'admin' };
}

export function knownToolNames(): string[] {
  return Object.keys(TOOL_ACTIONS).sort();
}
